PPTP-1659: Do you want to start your return?
hmrc/plastic-packaging-tax-returns-frontend pull request #113
Opened 2022-03-07 13:36 UTC by C-Thomp

- Start date returns page /start-date created with tests for controller, form and the view.
- Obligations api connected up.

**NOTE:** ticket was to create two pages, /start-date-not-recognised. This page hasn't been completed yet due to shift in print priorities.

#### Check list 
 - [ x] `./precheck` was executed (Integration/Component/Unit tests)
 - [x ] `sbt scalafmt test:scalafmt` was executed 
 - [ ] Required Environment Config has been amended/added
 - [ ] Links to dependencies have been included (BE/FE work)
 - [ ] User Acceptance Tests (UAT) were run locally and have passed.
 - [ ] No Accessibility errors/warnings reported by Wave

2022-03-07 16:02 UTC, RyanKellyHMRC requested changes
Looking good. There are few smaller changes worth making in my opinion and some bits which can be wired in now.

2022-03-07 16:02 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartDateReturnControllerTest.scala
> +        redirectLocation(result) mustBe Some(homeRoutes.HomeController.displayPage().url)
These pages should be available to be wired in now.

2022-03-07 16:32 UTC, liampan commented on app/uk/gov/hmrc/plasticpackagingtax/returns/controllers/returns/StartDateReturnController.scala
> +  def displayPage(): Action[AnyContent] = //TODO: which dates to populate title message?
Yes, its something that probably needs checked for the header section component thats already in main now. Unless you know thats right?

2022-03-07 17:08 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyAction.scala
> +                .getOrElse(throw new IllegalStateException(s"No Obligation for return id:$id"))
Actually, we had to make `obligation` optional in order to cater for existing in-flight returns which won't have one (these are created when the dashboard is accessed which happens after a successful registration). I don't think all users will have an outstanding obligation when they hit the dashboard. Can we remove the throwing of `IllegalStateException` and just set as `None` if there isn't one? We could then (probably a future ticket if we decide to bother) just tell the user that they do not have any open obligations if they try to access this flow - I imagine we would not present a link on the dashboard in this context.

2022-03-08 12:04 UTC, liampan commented on conf/messages.en
> -general.true = Yes
removing duplicates. lines 13, 14

2022-03-09 08:49 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyActionSpec.scala
> +        mockGetObligation()
If you used an `afterEach()` hook and reset mocks there then you could do "common" mock setup in `beforeEach()`. No need for a change - just a suggestion for the future.

2022-03-09 08:51 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtax/returns/models/request/JourneyAction.scala
> +                .getOrElse(throw new IllegalStateException(s"No Obligation for return id:$id"))
I think this is going to be a problem but we can address on a future ticket.

2022-03-09 08:52 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtax/returns/views/returns/start_date_returns_page.scala.html
> +                    classes = "govuk-fieldset__legend govuk-fieldset__legend govuk-fieldset__legend--l",
This has been done.

2022-03-09 08:52 UTC, RyanKellyHMRC approved these changes
Good work @C-Thomp. Thanks for making the suggested changes.

2022-03-10 10:17 UTC, merged